"""adicionando relacionamentos

Revision ID: 66d0c7f7d7c7
Revises: f1a8f6e4f54d
Create Date: 2024-08-04 20:51:06.391570

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66d0c7f7d7c7'
down_revision: Union[str, None] = 'f1a8f6e4f54d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('livros', sa.Column('ano', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('livros', 'ano')
    # ### end Alembic commands ###
